spring.datasource.url=jdbc:postgresql://caboose.proxy.rlwy.net:41523/railway
spring.datasource.username=postgres
spring.datasource.password= oNHjlthHhldkneTdHmPtWmvARcDgbnHt

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect